### ISSUE TITLE
Нерабочие примеры? 

### ISSUE THREAD

**Issue by Minuta18** [masterWeber/kinopoisk-api-unofficial-client#20]
Я использовал следующий код (из README):
```python
from kinopoisk_unofficial.kinopoisk_api_client import KinopoiskApiClient
from kinopoisk_unofficial.request.films.search_by_keyword_request import SearchByKeywordRequest

api_client = KinopoiskApiClient("token")
request = SearchByKeywordRequest("Kek")
response = api_client.films.send_search_by_keyword_request(request)
```
(Вместо "token" стоит токен)

Но я получил ошибку:

```
Traceback (most recent call last):
  File "/home/igors/Рабочий стол/archive/Main.py", line 6, in <module>
    response = api_client.films.send_search_by_keyword_request(request)
  File "/home/igors/Рабочий стол/archive/.venv/lib/python3.10/site-packages/kinopoisk_unofficial/client/films_api_client.py", line 38, in send_search_by_keyword_request
    return self._send_request(request)
  File "/home/igors/Рабочий стол/archive/.venv/lib/python3.10/site-packages/kinopoisk_unofficial/client/api_client.py", line 47, in _send_request
    return self.__deserialize_response(
  File "/home/igors/Рабочий стол/archive/.venv/lib/python3.10/site-packages/kinopoisk_unofficial/client/api_client.py", line 57, in __deserialize_response
    return self.__serializer.deserialize(response_class, response_body)
  File "/home/igors/Рабочий стол/archive/.venv/lib/python3.10/site-packages/apischema/utils.py", line 546, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/igors/Рабочий стол/archive/.venv/lib/python3.10/site-packages/apischema/deserialization/__init__.py", line 869, in deserialize
    return deserialization_method(
  File "/home/igors/Рабочий стол/archive/.venv/lib/python3.10/site-packages/apischema/deserialization/__init__.py", line 528, in method
    raise ValidationError(errors, field_errors)
apischema.validation.errors.ValidationError: ValidationError(messages=[], children={'keyword': ValidationError(messages=['missing property'], children={}), 'pagesCount': ValidationError(messages=['missing property'], children={}), 'searchFilmsCountResult': ValidationError(messages=['missing property'], children={})})
```

Как исправить?

**Comment by masterWeber** [comment]
Видимо изменился API, поробуйте просмотреть ответ, он соответствует схеме?

**Comment by Fan4Metal** [comment]
У меня этот код работает нормально. Python 3.10.8, kinopoisk-api-unofficial-client 2.2.2
